CREATE TABLE systems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    owner VARCHAR(160) NOT NULL,
    criticality VARCHAR(16) NOT NULL,
    expected_backup_interval_hours INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT systems_name_unique UNIQUE (name),
    CONSTRAINT systems_criticality_check CHECK (criticality IN ('Low', 'Medium', 'High', 'Critical')),
    CONSTRAINT systems_backup_interval_check CHECK (expected_backup_interval_hours BETWEEN 1 AND 8760)
);

CREATE TABLE backup_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL REFERENCES systems (id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    backup_type VARCHAR(16) NOT NULL,
    schedule_description VARCHAR(120) NOT NULL,
    max_runtime_minutes INTEGER NOT NULL DEFAULT 240,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT backup_jobs_system_name_unique UNIQUE (system_id, name),
    CONSTRAINT backup_jobs_type_check CHECK (backup_type IN ('Full', 'Incremental', 'Snapshot')),
    CONSTRAINT backup_jobs_runtime_check CHECK (max_runtime_minutes BETWEEN 1 AND 10080)
);

CREATE TABLE backup_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL REFERENCES systems (id) ON DELETE RESTRICT,
    backup_job_id BIGINT REFERENCES backup_jobs (id) ON DELETE SET NULL,
    external_id VARCHAR(160),
    backup_type VARCHAR(16) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    status VARCHAR(16) NOT NULL,
    size_bytes BIGINT,
    storage_location VARCHAR(500) NOT NULL,
    error_message VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT backup_runs_external_id_unique UNIQUE (external_id),
    CONSTRAINT backup_runs_type_check CHECK (backup_type IN ('Full', 'Incremental', 'Snapshot')),
    CONSTRAINT backup_runs_status_check CHECK (status IN ('Running', 'Successful', 'Failed', 'Cancelled')),
    CONSTRAINT backup_runs_size_check CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT backup_runs_time_check CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT backup_runs_completion_check CHECK (
        (status = 'Running' AND completed_at IS NULL)
        OR (status <> 'Running' AND completed_at IS NOT NULL)
    )
);

CREATE INDEX backup_jobs_system_id_idx ON backup_jobs (system_id);
CREATE INDEX backup_runs_system_started_idx ON backup_runs (system_id, started_at DESC);
CREATE INDEX backup_runs_status_started_idx ON backup_runs (status, started_at DESC);
CREATE INDEX backup_runs_job_id_idx ON backup_runs (backup_job_id) WHERE backup_job_id IS NOT NULL;
CREATE INDEX backup_runs_success_idx
    ON backup_runs (system_id, completed_at DESC)
    WHERE status = 'Successful';
CREATE INDEX backup_runs_running_idx
    ON backup_runs (started_at)
    WHERE status = 'Running';

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER systems_set_updated_at
BEFORE UPDATE ON systems
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER backup_jobs_set_updated_at
BEFORE UPDATE ON backup_jobs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE VIEW system_backup_health AS
WITH latest_success AS (
    SELECT DISTINCT ON (system_id)
        system_id,
        completed_at AS last_successful_at,
        size_bytes AS last_successful_size_bytes
    FROM backup_runs
    WHERE status = 'Successful'
    ORDER BY system_id, completed_at DESC
), latest_run AS (
    SELECT DISTINCT ON (system_id)
        system_id,
        status AS last_run_status,
        started_at AS last_run_started_at
    FROM backup_runs
    ORDER BY system_id, started_at DESC
)
SELECT
    s.id,
    s.name,
    s.owner,
    s.criticality,
    s.expected_backup_interval_hours,
    ls.last_successful_at,
    ls.last_successful_size_bytes,
    lr.last_run_status,
    lr.last_run_started_at,
    ls.last_successful_at + (s.expected_backup_interval_hours * INTERVAL '1 hour') AS next_backup_due_at,
    CASE
        WHEN ls.last_successful_at IS NULL THEN 'Never backed up'
        WHEN ls.last_successful_at + (s.expected_backup_interval_hours * INTERVAL '1 hour') < NOW() THEN 'Overdue'
        ELSE 'Healthy'
    END AS health_status
FROM systems s
LEFT JOIN latest_success ls ON ls.system_id = s.id
LEFT JOIN latest_run lr ON lr.system_id = s.id;

